---@alias norns.params.BinaryBehaviorType
---| "trigger" # (default)
---| "momentary"
---| "toggle"

---@class norns.params.BinaryParam : norns.params.Param
---@field default number
---@field value number
---@field behavior norns.params.BinaryBehaviorType
---@field allow_pmap boolean
---@field action fun(value: number)
